apiVersion: v1
kind: Secret
metadata:
  name: coreai-api-secrets
  namespace: coreai
type: Opaque
stringData:
  openai_api_key: sk-proj-QZndmuw20NrKH0UjnmITT3BlbkFJkC5S2wTLNHFcSuoGiu3C
  anthropic_api_key: sk-ant-api03-LA1_dpdI8GSNrZSft0iv3XrDIkOiZ7nAe5joJIBw74r_JUDrPlSaz0vjRbMjUxSGulRNZZZP_mA-fVNweKk2VRVnocd58
  gemini_api_key: AIzaSywPlvA0DTK1n0TYwMlQSajNuMKNdcffYEA
  grok_api_key: xai-zcc07T5Pyx0Zje0U2Tz29C7EJYvUNi7FkxvfNp4S46v6s5NhWiH4
  deepseek_api_key: sk-WDNhbyQTSsFCDSUI6Z5ynu021LkYYWFo
  database_url: postgresql://coreai_prod_user:DI235^yzhsp23ZN@prod-db.coreai.us-east-1.rds.amazonaws.com:5432/coreai_production
  redis_url: redis://:CZ347#cocvf85JK@prod-cache-cluster.6e7f1a.ng.0001.use1.cache.amazonaws.com:6379
  jwt_secret: cXJthHTJXECZqisR-Er4hBADb2WVh6QR2GZyabBRLQ25_wELrBwg4q15i-5x7Fny
  stripe_secret: sk_live_Fano4VS1FEeAiTWgNNQv7cEmJd2qmhBClSbvKEsCRDO2cwCR
  sentry_dsn: https://6e77194c0fef0107@o982341.ingest.sentry.io/5841209

---
apiVersion: v1
kind: Secret
metadata:
  name: coreai-docker-registry
  namespace: coreai
type: kubernetes.io/dockercfg
data:
  .dockercfg: eyIyODU2MTUyMzIxMTUuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHsidXNlcm5hbWUiOiAiQVdTIiwgInBhc3N3b3JkIjogIkRBT0RGaWtlWmRhRUhGczRQNmJUSUNOWG0zNjlNYjBmU1EwMUJpY09mUEFTS2V0MkwxTW5oQz1MMWRuYVlQY285bFducG5CcGZMMlF5RmMvIiwgImF1dGgiOiAiUVZkVE9rUkJUMFJHYVd0bFdtUmhSVWhHY3pSUU5tSlVTVU5PV0cwek5qbE5ZakJtVTFFd01VSnBZMDltVUVGVFMyVjBNa3d4VFc1b1F6MU1NV1J1WVZsUVkyODViRmR1Y0c1Q2NHWk1NbEY1Um1NdiJ9fQ==
